import AuthLayout from "@/layouts/auth.layout";
import {
  Box,
  Button,
  Container,
  Heading,
  Input,
  InputGroup,
  InputLeftElement,
  InputRightElement,
  Stack,
} from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import { AiOutlineKey, AiOutlineUser } from "react-icons/ai";
const Login = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Container>
          <form>
            <Stack
              spacing={4}
              minH={"calc(100vh)"}
              justifyContent={"center"}
              alignItems="center"
            >
              <Heading>Preparation Login</Heading>
              <InputGroup>
                <InputLeftElement pointerEvents="none">
                  <AiOutlineUser color="gray.300" />
                </InputLeftElement>
                <Input type="email" placeholder="Enter your email" />
              </InputGroup>
              <InputGroup>
                <InputLeftElement
                  pointerEvents="none"
                  color="gray.300"
                  fontSize="1.2em"
                  children=""
                />
                <Input type="password" placeholder="Enter your password" />
                <InputLeftElement>
                  <AiOutlineKey color="green.500" />
                </InputLeftElement>
              </InputGroup>
              <Button
                variant={"outline"}
                colorScheme="messenger"
                width={"100%"}
              >
                Login
              </Button>
            </Stack>
          </form>
        </Container>
      </Box>
    </>
  );
};

export default Login;
Login.getLayout = function getLayout(page) {
  return <AuthLayout>{page}</AuthLayout>;
};
