import AuthLayout from "@/layouts/auth.layout";
import {
  Box,
  Button,
  Container,
  Heading,
  Input,
  InputGroup,
  InputLeftElement,
  InputRightElement,
  Stack,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import React from "react";
import { AiOutlineKey, AiOutlineUser } from "react-icons/ai";
import { useRouter } from "next/router";
const Login = () => {
  const route = useRouter();
  const { data: session } = useSession();
  // console.log("session data", session);
  if (session) {
    return (
      <>
        <Text> Signed in as {session.user.email}</Text>;
        <button onClick={() => signOut()}>Sign out</button>
      </>
    );
  }
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Container>
          {/* <form>
            <Stack
              spacing={4}
              minH={"calc(100vh)"}
              justifyContent={"center"}
              alignItems="center"
            >
              <Heading>Preparation Login</Heading>
              <InputGroup>
                <InputLeftElement pointerEvents="none">
                  <AiOutlineUser color="gray.300" />
                </InputLeftElement>
                <Input type="email" placeholder="Enter your email" />
              </InputGroup>
              <InputGroup>
                <InputLeftElement
                  pointerEvents="none"
                  color="gray.300"
                  fontSize="1.2em"
                  children=""
                />
                <Input type="password" placeholder="Enter your password" />
                <InputLeftElement>
                  <AiOutlineKey color="green.500" />
                </InputLeftElement>
              </InputGroup>
              <Button
                variant={"outline"}
                colorScheme="messenger"
                width={"100%"}
              >
                Login
              </Button>
            </Stack>
          </form> */}
          <Stack
            spacing={4}
            minH={"calc(100vh)"}
            justifyContent={"center"}
            alignItems="center"
          >
            <Heading>Login</Heading>
            <Button
              variant="solid"
              colorScheme="messenger"
              onClick={() => signIn()}
            >
              Sign With Github
            </Button>
          </Stack>
        </Container>
      </Box>
    </>
  );
};

export default Login;
Login.getLayout = function getLayout(page) {
  return <AuthLayout>{page}</AuthLayout>;
};
