import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Center,
  Container,
  Grid,
  GridItem,
  Heading,
} from "@chakra-ui/react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import MainLayout from "@/layouts/main.layout";
const Home = () => {
  const { isLoading, error, data } = useQuery({
    queryKey: ["techData"],
    queryFn: () =>
      fetch("http://localhost:5000/api/v1/alltech").then((res) => res.json()),
  });

  if (isLoading) return "Loading...";

  if (error) return "An error has occurred: " + error.message;

  return (
    <>
      <Head>
        <title>Prepare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box maxH="calc(100vh)">
        <Container maxW={"contianer.lg"} centerContent>
          <Heading textAlign={"center"} my={10}>
            Interview Questions
          </Heading>
          <Grid templateColumns="repeat(3, 1fr)" gap={6}>
            {data.map((item, idx) => {
              return (
                <GridItem key={idx}>
                  <Link
                    href={{
                      pathname: `/${item.page}`,
                      query: {
                        content: `${item.technology}`,
                        page: `${item.page}`,
                      },
                    }}
                  >
                    <Box
                      p={10}
                      bg={"gray.300"}
                      textAlign={"center"}
                      rounded="lg"
                    >
                      <Heading textTransform={"uppercase"} size={"lg"}>
                        {item.technology}
                      </Heading>
                    </Box>
                  </Link>
                </GridItem>
              );
            })}
          </Grid>
        </Container>
      </Box>
    </>
  );
};
export default Home;
Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>;
};
